name: SCAPIS_AIDA
channels:
  - pytorch
  - nvidia
dependencies:
  - python = 3.9
  - pip
  - numpy=1.20
  - click>=8.0
  - pillow=9.2.0
  - scipy=1.7.1
  - pytorch=1.9.1
  - cudatoolkit=11.1
  - requests=2.26.0
  - tqdm=4.62.2
  - ninja=1.10.2
  - matplotlib=3.4.2
  - imageio=2.9.0
  - pip:
    - imgui==1.3.0
    - glfw==2.2.0
    - pyopengl==3.1.5
    - imageio-ffmpeg==0.4.3
    - pyspng
    - click==8.0.4
    - matplotlib==3.5.1
    - opencv-python-headless
    - pandas==1.4.2
    - pydicom==2.3.0
    - requests==2.27.1
    - SimpleITK==2.2.0
    - pylibjpeg[all]

